# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Verb.ui'
#
# Created: Sat Feb  5 14:25:12 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(714, 522)
        self.horizontalLayout_6 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalFrame = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setMargin(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.verticalFrame)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lWords = QtGui.QListWidget(self.verticalFrame)
        self.lWords.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lWords.setObjectName("lWords")
        self.verticalLayout.addWidget(self.lWords)
        self.bRemove = QtGui.QPushButton(self.verticalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRemove.sizePolicy().hasHeightForWidth())
        self.bRemove.setSizePolicy(sizePolicy)
        self.bRemove.setObjectName("bRemove")
        self.verticalLayout.addWidget(self.bRemove)
        self.horizontalLayout_6.addWidget(self.verticalFrame)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.singularLabel = QtGui.QLabel(Form)
        self.singularLabel.setObjectName("singularLabel")
        self.gridLayout.addWidget(self.singularLabel, 0, 0, 1, 1)
        self.tPresent = QtGui.QLineEdit(Form)
        self.tPresent.setObjectName("tPresent")
        self.gridLayout.addWidget(self.tPresent, 0, 1, 1, 1)
        self.singularSyllablesLabel = QtGui.QLabel(Form)
        self.singularSyllablesLabel.setObjectName("singularSyllablesLabel")
        self.gridLayout.addWidget(self.singularSyllablesLabel, 1, 0, 1, 1)
        self.presentSyl = QtGui.QSpinBox(Form)
        self.presentSyl.setMaximumSize(QtCore.QSize(60, 16777215))
        self.presentSyl.setObjectName("presentSyl")
        self.gridLayout.addWidget(self.presentSyl, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.pluralLabel = QtGui.QLabel(Form)
        self.pluralLabel.setObjectName("pluralLabel")
        self.gridLayout.addWidget(self.pluralLabel, 3, 0, 1, 1)
        self.tPart = QtGui.QLineEdit(Form)
        self.tPart.setObjectName("tPart")
        self.gridLayout.addWidget(self.tPart, 3, 1, 1, 1)
        self.pluralSyllablesLabel = QtGui.QLabel(Form)
        self.pluralSyllablesLabel.setObjectName("pluralSyllablesLabel")
        self.gridLayout.addWidget(self.pluralSyllablesLabel, 4, 0, 1, 1)
        self.partSyl = QtGui.QSpinBox(Form)
        self.partSyl.setMaximumSize(QtCore.QSize(60, 16777215))
        self.partSyl.setObjectName("partSyl")
        self.gridLayout.addWidget(self.partSyl, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.pastLabel = QtGui.QLabel(Form)
        self.pastLabel.setObjectName("pastLabel")
        self.gridLayout.addWidget(self.pastLabel, 6, 0, 1, 1)
        self.tPast = QtGui.QLineEdit(Form)
        self.tPast.setObjectName("tPast")
        self.gridLayout.addWidget(self.tPast, 6, 1, 1, 1)
        self.pastSyllablesLabel = QtGui.QLabel(Form)
        self.pastSyllablesLabel.setObjectName("pastSyllablesLabel")
        self.gridLayout.addWidget(self.pastSyllablesLabel, 7, 0, 1, 1)
        self.pastSyl = QtGui.QSpinBox(Form)
        self.pastSyl.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pastSyl.setObjectName("pastSyl")
        self.gridLayout.addWidget(self.pastSyl, 7, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 8, 1, 1, 1)
        self.pastParticipleLabel = QtGui.QLabel(Form)
        self.pastParticipleLabel.setObjectName("pastParticipleLabel")
        self.gridLayout.addWidget(self.pastParticipleLabel, 9, 0, 1, 1)
        self.tPastpart = QtGui.QLineEdit(Form)
        self.tPastpart.setObjectName("tPastpart")
        self.gridLayout.addWidget(self.tPastpart, 9, 1, 1, 1)
        self.pastPartSyllablesLabel = QtGui.QLabel(Form)
        self.pastPartSyllablesLabel.setObjectName("pastPartSyllablesLabel")
        self.gridLayout.addWidget(self.pastPartSyllablesLabel, 10, 0, 1, 1)
        self.pastpartSyl = QtGui.QSpinBox(Form)
        self.pastpartSyl.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pastpartSyl.setObjectName("pastpartSyl")
        self.gridLayout.addWidget(self.pastpartSyl, 10, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 11, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 12, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 13, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_4 = QtGui.QCheckBox(Form)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_3 = QtGui.QCheckBox(Form)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_5 = QtGui.QCheckBox(Form)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.gridLayout.addLayout(self.horizontalLayout, 14, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 2000, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem4, 15, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.bAdd = QtGui.QPushButton(Form)
        self.bAdd.setObjectName("bAdd")
        self.horizontalLayout_3.addWidget(self.bAdd)
        self.gridLayout.addLayout(self.horizontalLayout_3, 16, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Verbs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Verbs (Present):", None, QtGui.QApplication.UnicodeUTF8))
        self.bRemove.setText(QtGui.QApplication.translate("Form", "Remove Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.singularLabel.setText(QtGui.QApplication.translate("Form", "Present:", None, QtGui.QApplication.UnicodeUTF8))
        self.singularSyllablesLabel.setText(QtGui.QApplication.translate("Form", "Present Syllables:", None, QtGui.QApplication.UnicodeUTF8))
        self.pluralLabel.setText(QtGui.QApplication.translate("Form", "Participle:", None, QtGui.QApplication.UnicodeUTF8))
        self.pluralSyllablesLabel.setText(QtGui.QApplication.translate("Form", "Participle Syllables:", None, QtGui.QApplication.UnicodeUTF8))
        self.pastLabel.setText(QtGui.QApplication.translate("Form", "Past:", None, QtGui.QApplication.UnicodeUTF8))
        self.pastSyllablesLabel.setText(QtGui.QApplication.translate("Form", "Past Syllables", None, QtGui.QApplication.UnicodeUTF8))
        self.pastParticipleLabel.setText(QtGui.QApplication.translate("Form", "Past Participle", None, QtGui.QApplication.UnicodeUTF8))
        self.pastPartSyllablesLabel.setText(QtGui.QApplication.translate("Form", "Past Part Syllables:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "Intransitive", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Form", "Transitive", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Form", "Linking", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Form", "To Nouns", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Form", "To Adjetives", None, QtGui.QApplication.UnicodeUTF8))
        self.bAdd.setText(QtGui.QApplication.translate("Form", "Add/Update Entry", None, QtGui.QApplication.UnicodeUTF8))

