
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA Files;

SET search_path TO FILES,"$user",public;

CREATE TABLE Files.FileUpload
(
	fileUploadId SERIAL NOT NULL,
	mimeType CHARACTER VARYING(250) NOT NULL,
	fileData BYTEA NOT NULL,
	ATime TIMESTAMP NOT NULL,
	ETag CHARACTER VARYING(250) NOT NULL,
	fileName CHARACTER VARYING(1000) NOT NULL,
	URL CHARACTER VARYING(65000),
	CONSTRAINT FileUpload_PK PRIMARY KEY(fileUploadId)
);

COMMIT WORK;
