
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA IMEAD;

SET search_path TO IMEAD,"$user",public;

CREATE TABLE IMEAD.KeyValue
(
	key CHARACTER VARYING(1000) NOT NULL,
	"value" CHARACTER VARYING NOT NULL,
	CONSTRAINT KeyValue_PK PRIMARY KEY(key)
);

CREATE TABLE IMEAD.Localization
(
	key CHARACTER VARYING(1000) NOT NULL,
	localeCode CHARACTER VARYING(100) NOT NULL,
	"value" CHARACTER VARYING NOT NULL,
	CONSTRAINT Localization_PK PRIMARY KEY(localeCode, key)
);

COMMIT WORK;
