
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA toilet;

SET search_path TO TOILET,"$user",public;

CREATE TABLE toilet.Comment
(
	commentId SERIAL NOT NULL,
	articleId INTEGER NOT NULL,
	posted TIMESTAMP NOT NULL,
	postedHtml CHARACTER VARYING NOT NULL,
	postedName CHARACTER VARYING(250) NOT NULL,
	isApproved BOOLEAN,
	isSpam BOOLEAN,
	postedMarkdown CHARACTER VARYING,
	CONSTRAINT Comment_PK PRIMARY KEY(commentId)
);

CREATE TABLE toilet.Article
(
	articleId SERIAL NOT NULL,
	articleTitle CHARACTER VARYING(250) NOT NULL,
	ETag CHARACTER VARYING(250) NOT NULL,
	modified TIMESTAMP NOT NULL,
	posted TIMESTAMP NOT NULL,
	postedHtml CHARACTER VARYING NOT NULL,
	postedMarkdown CHARACTER VARYING NOT NULL,
	postedName CHARACTER VARYING(250) NOT NULL,
	sectionId INTEGER NOT NULL,
	comments BOOLEAN,
	description CHARACTER VARYING(1000),
	imageURL CHARACTER VARYING(1000),
	searchIndexData tsvector,
	summary CHARACTER VARYING(65000),
	URL CHARACTER VARYING(1000),
	postedAmp CHARACTER VARYING,
	searchableText CHARACTER VARYING,
	CONSTRAINT Article_PK PRIMARY KEY(articleId)
);

CREATE TABLE toilet.Section
(
	sectionId SERIAL NOT NULL,
	name CHARACTER VARYING(250) NOT NULL,
	CONSTRAINT Section_PK PRIMARY KEY(sectionId)
);

ALTER TABLE toilet.Comment ADD CONSTRAINT Comment_FK FOREIGN KEY (articleId) REFERENCES toilet.Article (articleId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE toilet.Article ADD CONSTRAINT Article_FK FOREIGN KEY (sectionId) REFERENCES toilet.Section (sectionId) ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;
