
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA toilet;

SET search_path TO TOILET,"$user",public;

CREATE TABLE toilet.URL
(
	URLId SERIAL NOT NULL,
	location CHARACTER VARYING(5000) NOT NULL,
	pageViews INTEGER,
	CONSTRAINT URL_PK PRIMARY KEY(URLId),
	CONSTRAINT URL_UC UNIQUE(location)
);

CREATE TABLE toilet.Comment
(
	commentId SERIAL NOT NULL,
	articleId INTEGER NOT NULL,
	posted TIMESTAMP NOT NULL,
	postedHtml CHARACTER VARYING NOT NULL,
	postedName CHARACTER VARYING(250) NOT NULL,
	isApproved BOOLEAN,
	isSpam BOOLEAN,
	postedMarkdown CHARACTER VARYING,
	CONSTRAINT Comment_PK PRIMARY KEY(commentId)
);

CREATE TABLE toilet.Article
(
	articleId SERIAL NOT NULL,
	articleTitle CHARACTER VARYING(250) NOT NULL,
	ETag CHARACTER VARYING(250) NOT NULL,
	modified TIMESTAMP NOT NULL,
	posted TIMESTAMP NOT NULL,
	postedHtml CHARACTER VARYING NOT NULL,
	postedMarkdown CHARACTER VARYING NOT NULL,
	postedName CHARACTER VARYING(250) NOT NULL,
	sectionId INTEGER NOT NULL,
	comments BOOLEAN,
	description CHARACTER VARYING(1000),
	URLId INTEGER,
	CONSTRAINT Article_PK PRIMARY KEY(articleId)
);

CREATE TABLE toilet.Section
(
	sectionId SERIAL NOT NULL,
	name CHARACTER VARYING(250) NOT NULL,
	CONSTRAINT Section_PK PRIMARY KEY(sectionId)
);

CREATE TABLE toilet.FileUpload
(
	fileUploadId SERIAL NOT NULL,
	binaryData BYTEA NOT NULL,
	ETag CHARACTER VARYING(250) NOT NULL,
	fileName CHARACTER VARYING(1000) NOT NULL,
	mimeType CHARACTER VARYING(250) NOT NULL,
	uploaded TIMESTAMP NOT NULL,
	URLId INTEGER,
	CONSTRAINT FileUpload_PK PRIMARY KEY(fileUploadId),
	CONSTRAINT FileUpload_UC UNIQUE(fileName)
);

CREATE TABLE toilet.ErrorEvent
(
	errorEventId SERIAL NOT NULL,
	ATime TIMESTAMP NOT NULL,
	description CHARACTER VARYING(65000) NOT NULL,
	title CHARACTER VARYING NOT NULL,
	CONSTRAINT ErrorEvent_PK PRIMARY KEY(errorEventId)
);

ALTER TABLE toilet.Comment ADD CONSTRAINT Comment_FK FOREIGN KEY (articleId) REFERENCES toilet.Article (articleId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE toilet.Article ADD CONSTRAINT Article_FK1 FOREIGN KEY (URLId) REFERENCES toilet.URL (URLId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE toilet.Article ADD CONSTRAINT Article_FK2 FOREIGN KEY (sectionId) REFERENCES toilet.Section (sectionId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE toilet.FileUpload ADD CONSTRAINT FileUpload_FK FOREIGN KEY (URLId) REFERENCES toilet.URL (URLId) ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;
